import {
  FaTh,
  FaCalendarAlt,
  FaUserCircle,
  FaList,
  FaTable,
  FaFileAlt,
  FaChartPie,
  FaCube,
  FaPlug,
  FaChevronDown,
  FaEllipsisH,
  FaBookOpen,
  FaCalendarDay,
  FaGraduationCap,
  FaUsers,
  FaCog,
  FaChartBar,
  FaClipboardList,
  FaEnvelope,
  FaCreditCard
} from 'react-icons/fa';

export {
  FaTh as GridIcon,
  FaCalendarAlt as CalenderIcon,
  FaUserCircle as UserCircleIcon,
  FaList as ListIcon,
  FaTable as TableIcon,
  FaFileAlt as PageIcon,
  FaChartPie as PieChartIcon,
  FaCube as BoxCubeIcon,
  FaPlug as PlugInIcon,
  FaChevronDown as ChevronDownIcon,
  FaEllipsisH as HorizontaLDots,
  FaBookOpen as BookOpenIcon,
  FaCalendarDay as CalendarDaysIcon,
  FaGraduationCap as GraduationCapIcon,
  FaUsers as UsersIcon,
  FaCog as SettingsIcon,
  FaChartBar as BarChartIcon,
  FaClipboardList as ClipboardListIcon,
  FaEnvelope as EnvelopeIcon,
  FaCreditCard as CreditCardIcon,
};
